<template>
  <div class="app-container">
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="90px">
      <el-form-item label="order code" prop="code">
        <el-input v-model="queryParams.code" placeholder="请输入Order code" clearable @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item label="Status" prop="status">
        <el-select v-model="queryParams.status" placeholder="请选择Status" clearable>
          <el-option v-for="dict in order_status" :key="dict.value" :label="dict.label" :value="dict.value" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['manage:order:add']">新增</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate"
          v-hasPermi="['manage:order:edit']">修改</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete"
          v-hasPermi="['manage:order:remove']">删除</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="warning" plain icon="Download" @click="handleExport"
          v-hasPermi="['manage:order:export']">导出</el-button>
      </el-col>
      <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
    </el-row>

    <el-table v-loading="loading" :data="orderList" @selection-change="handleSelectionChange">
      <el-table-column type="selection" width="55" align="center" />
      <el-table-column label="seq." type="index" align="center" width="80" />
      <el-table-column label="order code" align="center" prop="code" />
      <el-table-column label="status" align="center" prop="status">
        <template #default="scope">
          <dict-tag :options="order_status" :value="scope.row.status" />
        </template>
      </el-table-column>
      <el-table-column label="generated type" align="center" prop="isAutoGenerated">
        <template #default="scope">
          <dict-tag :options="is_auto_generated" :value="scope.row.isAutoGenerated" />
        </template>
      </el-table-column>
      <el-table-column label="vm inner code" align="center" prop="vmInnerCode" />
      <el-table-column label="user" align="center" prop="userId" />
      <el-table-column label="type" align="center" prop="type" />
      <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
        <template #default="scope">
          <el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)"
            v-hasPermi="['manage:order:edit']">修改</el-button>
          <el-button link type="primary" icon="Delete" @click="handleDelete(scope.row)"
            v-hasPermi="['manage:order:remove']">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum"
      v-model:limit="queryParams.pageSize" @pagination="getList" />

    <!-- 添加或修改Order table对话框 -->
    <el-dialog :title="title" v-model="open" width="500px" append-to-body>
      <el-form ref="orderRef" :model="form" :rules="rules" label-width="120px">
        <el-form-item label="vm inner code" prop="vmInnerCode">
          <!--// NOTE:after change the vmInnerCode, the userId will be reset-->
          <el-select v-model="form.vmInnerCode" placeholder="请选择VM inner code"
            @change="() => { form.userId = ''; handleVmInnerCodeChange(); }">
            <el-option v-for="item in vmList" :key="item.id" :label="item.innerCode" :value="item.innerCode"
              @click="form.regionId = item.regionId"></el-option>
          </el-select>
        </el-form-item>

        <el-form-item label="user" prop="userId">
          <el-select v-model="form.userId" placeholder="请选择User ID">
            <el-option v-for="item in empList" :key="item.id" :label="item.userName" :value="item.id"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item prop="vmInnerCode">
          <el-button label="supply order" type="primary" @click="getListAisleByVmCode(form.vmInnerCode)">supply
            order</el-button>
          <span v-if="!form.vmInnerCode" style="color: red;">VM Inner Code is undefined</span>
        </el-form-item>

        <el-form-item label="region" prop="regionId">
          <span v-if="form.regionId">{{ regionList.find(item => item.id === form.regionId)?.name }}</span>
        </el-form-item>
        <el-form-item label="type" prop="type">
          <el-select v-model="form.type" placeholder="请选择Type">
            <el-option v-for="item in orderTypeList" :key="item.id" :label="item.name" :value="item.id"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="description" prop="description">
          <el-input v-model="form.description" type="textarea" placeholder="请输入内容" />
        </el-form-item>
        <el-form-item label="assignor" prop="assignorId">
          <el-input v-model="form.assignorId" placeholder="请输入Assignor ID" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <el-dialog v-model="openDialog" title="添加" width="80%">
      <el-table v-loading="loading" :data="aisleList" @selection-change="handleSelectionChange">
        <el-table-column label="seq." type="index" align="center" width="80" />
        <el-table-column label="aisle code" align="center" prop="code" />
        <el-table-column label="goods name" align="center" prop="goodsId">
          <template #default="scope">
            <span>{{ goodsList.find(item => item.id === scope.row.goodsId)?.name }}</span>
          </template>
        </el-table-column>
        <el-table-column label="current volumn" align="center" prop="currentCapacity" />
        <el-table-column label="available volumn" align="center" prop="maxCapacity" />
        <el-table-column label="supply volume" align="center">
          <template #default="scope">
            <el-input-number v-model="scope.row.supplyVolume" :min="0"
              :max="scope.row.maxCapacity - scope.row.currentCapacity"
              @change="scope.row.currentCapacity += scope.row.supplyVolume" /><!--NOTE:after change the supplyVolume, the currentCapacity will be reset-->
          </template>
        </el-table-column>
      </el-table>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="openDialog = false">取消</el-button>
          <el-button type="primary" @click="handleSubmit">确定</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Order">
import { listOrder, getOrder, delOrder, addOrder, updateOrder } from "@/api/manage/order";
import { listVm } from "@/api/manage/vm";
import { loadAllParams } from "@/api/page";
import { listOperatorByInnerCode } from "@/api/manage/emp";
import { listRegion } from "@/api/manage/region";
import { listOrderTypeByParentId } from "@/api/manage/order_type";
import { listAisleByVmCode } from "@/api/manage/aisle";
import { listGoods } from "@/api/manage/goods";
import { get } from "@vueuse/core";
const { proxy } = getCurrentInstance();
const { order_status, is_auto_generated } = proxy.useDict('order_status', 'is_auto_generated');

const orderList = ref([]);
const open = ref(false);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const title = ref("");
const openDialog = ref(false);


const data = reactive({
  form: {},
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    innerCode: null,
    code: null,
    status: null,
    params: {
      parentTypeId: 1,  // parentTypeId of operation order is 1.
    },
  },

  rules: {
    vmInnerCode: [
      { required: true, message: "vm innner code不能为空", trigger: "blur" }
    ],
  }
});

const { queryParams, form, rules } = toRefs(data);

/** 查询Order table列表 */
function getList() {
  loading.value = true;
  listOrder(queryParams.value).then(response => {
    orderList.value = response.rows;
    total.value = response.total;
    loading.value = false;
  });
}

// 取消按钮
function cancel() {
  open.value = false;
  reset();
}

// 表单重置
function reset() {
  form.value = {
    id: null,
    code: null,
    status: null,
    isAutoGenerated: null,
    vmInnerCode: null,
    userId: null,
    regionId: null,
    description: null,
    type: null,
    assignorId: null,
    createTime: null,
    updateTime: null
  };
  proxy.resetForm("orderRef");
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1;
  getList();
}

/** 重置按钮操作 */
function resetQuery() {
  proxy.resetForm("queryRef");
  handleQuery();
}

// 多选框选中数据
function handleSelectionChange(selection) {
  ids.value = selection.map(item => item.id);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
}

/** 新增按钮操作 */
function handleAdd() {
  reset();
  open.value = true;
  title.value = "添加Order table";
}

/** 修改按钮操作 */
function handleUpdate(row) {
  reset();
  const _id = row.id || ids.value
  getOrder(_id).then(response => {
    form.value = response.data;
    open.value = true;
    title.value = "修改Order table";
    handleVmInnerCodeChange();//NOTE: empList should be preloaded in advance
  });
}

/** 提交按钮 */
function submitForm() {
  proxy.$refs["orderRef"].validate(valid => {
    if (valid) {
      if (form.value.id != null) {
        updateOrder({
          createType: 1,// operation order is 1
          vmInnerCode: form.value.vmInnerCode,
          userId: form.value.userId,
          assignorId: form.value.assignorId,
          typeId: form.value.type,
          description: form.value.description,
          details: aisleList.value.filter(aisle => aisle.innerCode === form.value.vmInnerCode).map(item => ({
            aisleCode: item.code,
            availableCapacity: item.maxCapacity - item.currentCapacity,
            goodsId: item.goodsId,
            goodsName: item.goods.goodsName,
            goodsImage: item.goods.goodsImage,
          })),
        }).then(response => {
          proxy.$modal.msgSuccess("修改成功");
          open.value = false;
          getList();
        });
      } else {
        addOrder({
          createType: 1,// operation order is 1
          vmInnerCode: form.value.vmInnerCode,
          userId: form.value.userId,
          assignorId: form.value.assignorId,
          typeId: form.value.type,
          description: form.value.description,
          details: aisleList.value.filter(aisle => aisle.innerCode === form.value.vmInnerCode).map(item => ({
            aisleCode: item.code,
            availableCapacity: item.maxCapacity - item.currentCapacity,
            goodsId: item.goodsId,
            goodsName: item.goods.goodsName,
            goodsImage: item.goods.goodsImage,
          })),
        }).then(response => {
          proxy.$modal.msgSuccess("新增成功");
          open.value = false;
          getList();
        });
      }
    }
  });
}

/** 删除按钮操作 */
function handleDelete(row) {
  const _ids = row.id || ids.value;
  proxy.$modal.confirm('是否确认删除Order table编号为"' + _ids + '"的数据项？').then(function () {
    return delOrder(_ids);
  }).then(() => {
    getList();
    proxy.$modal.msgSuccess("删除成功");
  }).catch(() => { });
}

/** 导出按钮操作 */
function handleExport() {
  proxy.download('manage/order/export', {
    ...queryParams.value
  }, `order_${new Date().getTime()}.xlsx`)
}
const empList = ref([]);
function handleVmInnerCodeChange() {
  let vmInnerCode = form.value.vmInnerCode;
  listOperatorByInnerCode(vmInnerCode).then(response => {
    empList.value = response.data;
    console.log(empList);
  });
}
const vmList = ref([]);
function getAllVmList() {
  listVm(loadAllParams).then(response => {
    vmList.value = response.rows;
  })
}
const regionList = ref([]);
function getAllRegionList() {
  listRegion(loadAllParams).then(response => {
    regionList.value = response.rows;
  })
}

const orderTypeList = ref([]);
/** get operation order type */
function getOperationOrderType() {
  listOrderTypeByParentId(queryParams.value.params.parentTypeId).then(response => {
    orderTypeList.value = response.data; //NOTE：it is response.data but not response.rows, why?
    console.log(orderTypeList.value);
  });
}
/** get aisle list */
const aisleList = ref([]);
function getListAisleByVmCode(vmInnerCode) {
  console.log(vmInnerCode);
  listAisleByVmCode(vmInnerCode).then(response => {
    aisleList.value = response.data;
    console.log(aisleList.value);
    openDialog.value = true;
  });
}
/** get goods list */
const goodsList = ref([]);
function getAllGoodsList() {
  listGoods(loadAllParams).then(response => {
    goodsList.value = response.rows;
    console.log(goodsList.value);
  })  
}
 function handleSubmit(){
openDialog.value = false;
 }

/** Preload data(Cache) */
getList();
getAllRegionList();
getAllVmList();
getOperationOrderType();
getAllGoodsList();
</script>
